Doesn't have strerror_r
due to below error.

/home/runner/work/my-emacs/my-emacs/my_sub_modules/my-Android-ImageMagick7//ImageMagick-7.1.0-62/MagickCore/exception.c:532:37: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
  (void) CopyMagickString(exception,strerror_r(error,exception,
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
https://github.com/emscripten-core/emscripten/issues/5849